[package]
name = "dsf-experiment-common"
version = "0.1.0"
edition = "2024"
[workspace]
[dependencies]
dsf-resource-common = { path = "../dsf_resource_common" }
serde_json = "1"
sha2 = "0.10"
base64 = "0.22"
[target.'cfg(target_arch = "wasm32")'.dependencies]
temper-wasm-sdk = { git = "https://github.com/arni-labs/temper.git", rev = "aead3d22c769382523430c7f769a1aea8486d360" }
